# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: form
      MONGO_USERNAME: root
      MONGO_PASSWORD: password

    ports:
      - '27018:27018'

  web:
    build: ./
    ports:
      - 3000:3000
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@172.19.0.2:27017/form

    depends_on:
      - db

# version: '3.3'
# services:
#   web:
#     build: ./
#       # context: .
#       # dockerfile: Dockerfile
#     ports:
#       - '3000:3000'
#     env_file: .env
#     environment:
#       - DATABASE_CONNECTION_STRING="mongodb://localhost:27017/forms"
#     depends_on:
#       - db

#   db:
#     image: mongo:latest
#     env_file: .env

#     environment:
#       - MONGO_INITDB_ROOT_USERNAME='root'
#       - MONGO_INITDB_ROOT_PASSWORD='password'
#       - MONGO_INITDB_DATABASE='forms'

#     ports:
#       - '27017:27017'